require 'rails_helper'
require 'rspec/char_field'
require 'rspec/text_field'

require 'respec/int_field'
# require 'respec/bignum_field'
# require 'respec/num_field'
# require 'respec/bigint_field'
# require 'respec/positive_bignum_field'
# require 'respec/positive_num_field'
# require 'respec/positive_bigint_field'
# require 'respec/positive_int_field'

# require 'respec/arr_field'
# require 'respec/hash_field'
# require 'respec/date_field'
# require 'respec/time_field'
# require 'respec/datetime_field'
# require 'respec/email_field'
# require 'respec/boolean_field'